<!DOCTYPE html>
<html>

<head>
   <title>Aione Colors</title>
   <!--Import Google Icon Font-->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

   <link type="text/css" rel="stylesheet" href="../assets/css/aione.css" media="screen,projection" />
   <!--Let browser know website is optimized for mobile-->
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
   <div class="ar m-30 aione-border">
      <div class="aione-title">
         <h4 class="aione-align-center font-weight-100 aione-border-bottom pb-15">Text Color</h4>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 red lighten-5">red lighten-1</div>
         <div class="p-10 red lighten-4">red lighten-2</div>
         <div class="p-10 red lighten-3">red lighten-3</div>
         <div class="p-10 red lighten-2">red lighten-4</div>
         <div class="p-10 red lighten-1">red lighten-5</div>
         <div class="p-10 red">red</div>
         <div class="p-10 red darken-1">red darken-1</div>
         <div class="p-10 red darken-2">red darken-2</div>
         <div class="p-10 red darken-3">red darken-3</div>
         <div class="p-10 red darken-4">red darken-4</div>
         <div class="p-10 red accent-1">red accent-1</div>
         <div class="p-10 red accent-2">red accent-2</div>
         <div class="p-10 red accent-3">red accent-3</div>
         <div class="p-10 red accent-4">red accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 pink lighten-5">pink lighten-1</div>
         <div class="p-10 pink lighten-4">pink lighten-2</div>
         <div class="p-10 pink lighten-3">pink lighten-3</div>
         <div class="p-10 pink lighten-2">pink lighten-4</div>
         <div class="p-10 pink lighten-1">pink lighten-5</div>
         <div class="p-10 pink">pink</div>
         <div class="p-10 pink darken-1">pink darken-1</div>
         <div class="p-10 pink darken-2">pink darken-2</div>
         <div class="p-10 pink darken-3">pink darken-3</div>
         <div class="p-10 pink darken-4">pink darken-4</div>
         <div class="p-10 pink accent-1">pink accent-1</div>
         <div class="p-10 pink accent-2">pink accent-2</div>
         <div class="p-10 pink accent-3">pink accent-3</div>
         <div class="p-10 pink accent-4">pink accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 purple lighten-5">purple lighten-1</div>
         <div class="p-10 purple lighten-4">purple lighten-2</div>
         <div class="p-10 purple lighten-3">purple lighten-3</div>
         <div class="p-10 purple lighten-2">purple lighten-4</div>
         <div class="p-10 purple lighten-1">purple lighten-5</div>
         <div class="p-10 purple">purple</div>
         <div class="p-10 purple darken-1">purple darken-1</div>
         <div class="p-10 purple darken-2">purple darken-2</div>
         <div class="p-10 purple darken-3">purple darken-3</div>
         <div class="p-10 purple darken-4">purple darken-4</div>
         <div class="p-10 purple accent-1">purple accent-1</div>
         <div class="p-10 purple accent-2">purple accent-2</div>
         <div class="p-10 purple accent-3">purple accent-3</div>
         <div class="p-10 purple accent-4">purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 deep-purple  lighten-5">deep-purple lighten-1</div>
         <div class="p-10 deep-purple  lighten-4">deep-purple lighten-2</div>
         <div class="p-10 deep-purple  lighten-3">deep-purple lighten-3</div>
         <div class="p-10 deep-purple  lighten-2">deep-purple lighten-4</div>
         <div class="p-10 deep-purple  lighten-1">deep-purple lighten-5</div>
         <div class="p-10 deep-purple ">deep-purple </div>
         <div class="p-10 deep-purple  darken-1">deep-purple darken-1</div>
         <div class="p-10 deep-purple  darken-2">deep-purple darken-2</div>
         <div class="p-10 deep-purple  darken-3">deep-purple darken-3</div>
         <div class="p-10 deep-purple  darken-4">deep-purple darken-4</div>
         <div class="p-10 deep-purple  accent-1">deep-purple accent-1</div>
         <div class="p-10 deep-purple  accent-2">deep-purple accent-2</div>
         <div class="p-10 deep-purple  accent-3">deep-purple accent-3</div>
         <div class="p-10 deep-purple  accent-4">deep-purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 indigo  lighten-5">indigo lighten-1</div>
         <div class="p-10 indigo  lighten-4">indigolighten-2</div>
         <div class="p-10 indigo  lighten-3">indigo lighten-3</div>
         <div class="p-10 indigo lighten-2">indigo lighten-4</div>
         <div class="p-10 indigo  lighten-1">indigo lighten-5</div>
         <div class="p-10 indigo ">indigo</div>
         <div class="p-10 indigo  darken-1">indigo darken-1</div>
         <div class="p-10 indigo  darken-2">indigo darken-2</div>
         <div class="p-10 indigo  darken-3">indigo darken-3</div>
         <div class="p-10 indigo  darken-4">indigo darken-4</div>
         <div class="p-10 indigo accent-1">indigo accent-1</div>
         <div class="p-10 indigo  accent-2">indigo accent-2</div>
         <div class="p-10 indigo  accent-3">indigo accent-3</div>
         <div class="p-10 indigo  accent-4">indigo accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 blue  lighten-5">blue lighten-1</div>
         <div class="p-10 blue  lighten-4">blue lighten-2</div>
         <div class="p-10 blue  lighten-3">blue lighten-3</div>
         <div class="p-10 blue lighten-2">blue lighten-4</div>
         <div class="p-10 blue  lighten-1">blue lighten-5</div>
         <div class="p-10 blue ">blue</div>
         <div class="p-10 blue  darken-1">blue darken-1</div>
         <div class="p-10 blue  darken-2">blue darken-2</div>
         <div class="p-10 blue  darken-3">blue darken-3</div>
         <div class="p-10 blue  darken-4">blue darken-4</div>
         <div class="p-10 blue accent-1">blue accent-1</div>
         <div class="p-10 blue  accent-2">blue accent-2</div>
         <div class="p-10 blue  accent-3">blue accent-3</div>
         <div class="p-10 blue  accent-4">blue accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 light-blue  lighten-5">light-blue lighten-1</div>
         <div class="p-10 light-blue  lighten-4">light-blue lighten-2</div>
         <div class="p-10 light-blue  lighten-3">light-blue lighten-3</div>
         <div class="p-10 light-blue lighten-2">light-blue lighten-4</div>
         <div class="p-10 light-blue  lighten-1">light-blue lighten-5</div>
         <div class="p-10 light-blue ">light-blue</div>
         <div class="p-10 light-blue  darken-1">light-blue darken-1</div>
         <div class="p-10 light-blue  darken-2">light-blue darken-2</div>
         <div class="p-10 light-blue  darken-3">light-blue darken-3</div>
         <div class="p-10 light-blue  darken-4">light-blue darken-4</div>
         <div class="p-10 light-blue accent-1">light-blue accent-1</div>
         <div class="p-10 light-blue  accent-2">light-blue accent-2</div>
         <div class="p-10 light-blue  accent-3">light-blue accent-3</div>
         <div class="p-10 light-blue  accent-4">light-blue accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 cyan lighten-5">cyan lighten-1</div>
         <div class="p-10 cyan lighten-4">cyan lighten-2</div>
         <div class="p-10 cyan  lighten-3">cyan lighten-3</div>
         <div class="p-10 cyan lighten-2">cyan lighten-4</div>
         <div class="p-10 cyan  lighten-1">cyan lighten-5</div>
         <div class="p-10 cyan ">cyan</div>
         <div class="p-10 cyan  darken-1">cyan darken-1</div>
         <div class="p-10 cyan  darken-2">cyan darken-2</div>
         <div class="p-10 cyan  darken-3">cyan darken-3</div>
         <div class="p-10 cyan  darken-4">cyan darken-4</div>
         <div class="p-10 cyan accent-1">cyan accent-1</div>
         <div class="p-10 cyan  accent-2">cyan accent-2</div>
         <div class="p-10 cyan  accent-3">cyan accent-3</div>
         <div class="p-10 cyan  accent-4">cyan accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 teal lighten-5">teal lighten-1</div>
         <div class="p-10 teal lighten-4">teal lighten-2</div>
         <div class="p-10 teal lighten-3">teal lighten-3</div>
         <div class="p-10 teal lighten-2">teal lighten-4</div>
         <div class="p-10 teal  lighten-1">teal lighten-5</div>
         <div class="p-10 teal">teal</div>
         <div class="p-10 teal  darken-1">teal darken-1</div>
         <div class="p-10 teal  darken-2">teal darken-2</div>
         <div class="p-10 teal  darken-3">teal darken-3</div>
         <div class="p-10 teal  darken-4">teal darken-4</div>
         <div class="p-10 teal accent-1">teal accent-1</div>
         <div class="p-10 teal  accent-2">teal accent-2</div>
         <div class="p-10 teal  accent-3">teal accent-3</div>
         <div class="p-10 teal  accent-4">teal accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 green lighten-5">green lighten-1</div>
         <div class="p-10 green lighten-4">green lighten-2</div>
         <div class="p-10 green lighten-3">green lighten-3</div>
         <div class="p-10 green lighten-2">green lighten-4</div>
         <div class="p-10 green  lighten-1">green lighten-5</div>
         <div class="p-10 green ">green</div>
         <div class="p-10 green  darken-1">green darken-1</div>
         <div class="p-10 green  darken-2">green darken-2</div>
         <div class="p-10 green  darken-3">green darken-3</div>
         <div class="p-10 green  darken-4">green darken-4</div>
         <div class="p-10 green accent-1">green accent-1</div>
         <div class="p-10 green  accent-2">green accent-2</div>
         <div class="p-10 green  accent-3">green accent-3</div>
         <div class="p-10 green  accent-4">green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10  light-green lighten-5">light-green lighten-1</div>
         <div class="p-10  light-green lighten-4">light-green lighten-2</div>
         <div class="p-10  light-green lighten-3">light-green lighten-3</div>
         <div class="p-10  light-green lighten-2">light-green lighten-4</div>
         <div class="p-10  light-green  lighten-1">green lighten-5</div>
         <div class="p-10  light-green "> light-green</div>
         <div class="p-10  light-green  darken-1">light-green darken-1</div>
         <div class="p-10  light-green  darken-2">light-green darken-2</div>
         <div class="p-10  light-green  darken-3">light-green darken-3</div>
         <div class="p-10  light-green  darken-4">light-green darken-4</div>
         <div class="p-10  light-green accent-1">light-green accent-1</div>
         <div class="p-10  light-green  accent-2">light-green accent-2</div>
         <div class="p-10  light-green  accent-3">light-green accent-3</div>
         <div class="p-10  light-green  accent-4">light-green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 lime lighten-5">lime lighten-1</div>
         <div class="p-10 lime lighten-4">lime lighten-2</div>
         <div class="p-10 lime lighten-3">lime lighten-3</div>
         <div class="p-10 lime lighten-2">lime lighten-4</div>
         <div class="p-10 lime  lighten-1">lime lighten-5</div>
         <div class="p-10 lime ">lime</div>
         <div class="p-10 lime  darken-1">lime darken-1</div>
         <div class="p-10 lime  darken-2">lime darken-2</div>
         <div class="p-10 lime  darken-3">lime darken-3</div>
         <div class="p-10 lime  darken-4">lime darken-4</div>
         <div class="p-10 lime accent-1">lime accent-1</div>
         <div class="p-10 lime  accent-2">lime accent-2</div>
         <div class="p-10 lime  accent-3">lime accent-3</div>
         <div class="p-10 lime  accent-4">lime accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 yellow lighten-5">yellow lighten-1</div>
         <div class="p-10 yellow lighten-4">yellow lighten-2</div>
         <div class="p-10 yellow lighten-3">yellow lighten-3</div>
         <div class="p-10 yellow lighten-2">yellow lighten-4</div>
         <div class="p-10 yellow  lighten-1">yellow lighten-5</div>
         <div class="p-10 yellow ">yellow</div>
         <div class="p-10 yellow  darken-1">yellow darken-1</div>
         <div class="p-10 yellow  darken-2">yellow darken-2</div>
         <div class="p-10 yellow  darken-3">yellow darken-3</div>
         <div class="p-10 yellow  darken-4">yellow darken-4</div>
         <div class="p-10 yellow accent-1">yellow accent-1</div>
         <div class="p-10 yellow  accent-2">yellow accent-2</div>
         <div class="p-10 yellow  accent-3">yellow accent-3</div>
         <div class="p-10 yellow  accent-4">yellow accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 amber lighten-5">amber lighten-1</div>
         <div class="p-10 amber lighten-4">amber lighten-2</div>
         <div class="p-10 amber lighten-3">amber lighten-3</div>
         <div class="p-10 amber lighten-2">amber lighten-4</div>
         <div class="p-10 amber  lighten-1">amber lighten-5</div>
         <div class="p-10 amber ">amber</div>
         <div class="p-10 amber  darken-1">amber darken-1</div>
         <div class="p-10 amber  darken-2">amber darken-2</div>
         <div class="p-10 amber  darken-3">amber darken-3</div>
         <div class="p-10 amber  darken-4">amber darken-4</div>
         <div class="p-10 amber accent-1">amber accent-1</div>
         <div class="p-10 amber  accent-2">amber accent-2</div>
         <div class="p-10 amber  accent-3">amber accent-3</div>
         <div class="p-10 amber  accent-4">amber accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 orange lighten-5">orange lighten-1</div>
         <div class="p-10 orange lighten-4">orange lighten-2</div>
         <div class="p-10 orange lighten-3">orange lighten-3</div>
         <div class="p-10 orange lighten-2">orange lighten-4</div>
         <div class="p-10 orange  lighten-1">orange lighten-5</div>
         <div class="p-10 orange ">orange</div>
         <div class="p-10 orange  darken-1">orange darken-1</div>
         <div class="p-10 orange  darken-2">orange darken-2</div>
         <div class="p-10 orange  darken-3">orange darken-3</div>
         <div class="p-10 orange  darken-4">orange darken-4</div>
         <div class="p-10 orange accent-1">orange accent-1</div>
         <div class="p-10 orange  accent-2">orange accent-2</div>
         <div class="p-10 orange  accent-3">orange accent-3</div>
         <div class="p-10 orange  accent-4">orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 deep-orange lighten-5">deep-orange lighten-1</div>
         <div class="p-10 deep-orange lighten-4">deep-orange lighten-2</div>
         <div class="p-10 deep-orange lighten-3">deep-orange lighten-3</div>
         <div class="p-10 deep-orange lighten-2">deep-orange lighten-4</div>
         <div class="p-10 deep-orange  lighten-1">deep-orange lighten-5</div>
         <div class="p-10 deep-orange ">deep-orange</div>
         <div class="p-10 deep-orange  darken-1">deep-orange darken-1</div>
         <div class="p-10 deep-orange  darken-2">deep-orange darken-2</div>
         <div class="p-10 deep-orange  darken-3">deep-orange darken-3</div>
         <div class="p-10 deep-orange  darken-4">deep-orange darken-4</div>
         <div class="p-10 deep-orange accent-1">deep-orange accent-1</div>
         <div class="p-10 deep-orange  accent-2">deep-orange accent-2</div>
         <div class="p-10 deep-orange  accent-3">deep-orange accent-3</div>
         <div class="p-10 deep-orange  accent-4">deep-orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 brown lighten-5">brown lighten-1</div>
         <div class="p-10 brown lighten-4">brown lighten-2</div>
         <div class="p-10 brown lighten-3">brown lighten-3</div>
         <div class="p-10 brown lighten-2">brown lighten-4</div>
         <div class="p-10 brown  lighten-1">brown lighten-5</div>
         <div class="p-10 brown ">brown</div>
         <div class="p-10 brown  darken-1">brown darken-1</div>
         <div class="p-10 brown  darken-2">brown darken-2</div>
         <div class="p-10 brown  darken-3">brown darken-3</div>
         <div class="p-10 brown  darken-4">brown darken-4</div>
         <div class="p-10 brown accent-1">brown accent-1</div>
         <div class="p-10 brown  accent-2">brown accent-2</div>
         <div class="p-10 brown  accent-3">brown accent-3</div>
         <div class="p-10 brown  accent-4">brown accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 grey lighten-5">grey lighten-1</div>
         <div class="p-10 grey lighten-4">grey lighten-2</div>
         <div class="p-10 grey lighten-3">grey lighten-3</div>
         <div class="p-10 grey lighten-2">grey lighten-4</div>
         <div class="p-10 grey  lighten-1">grey lighten-5</div>
         <div class="p-10 grey ">grey</div>
         <div class="p-10 grey  darken-1">grey darken-1</div>
         <div class="p-10 grey  darken-2">grey darken-2</div>
         <div class="p-10 grey  darken-3">grey darken-3</div>
         <div class="p-10 grey  darken-4">grey darken-4</div>
         <div class="p-10 grey accent-1">grey accent-1</div>
         <div class="p-10 grey  accent-2">grey accent-2</div>
         <div class="p-10 grey  accent-3">grey accent-3</div>
         <div class="p-10 grey  accent-4">grey accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 blue-grey lighten-5">blue-grey lighten-1</div>
         <div class="p-10 blue-grey lighten-4">blue-grey lighten-2</div>
         <div class="p-10 blue-grey lighten-3">blue-grey lighten-3</div>
         <div class="p-10 blue-grey lighten-2">blue-grey lighten-4</div>
         <div class="p-10 blue-grey lighten-1">blue-grey lighten-5</div>
         <div class="p-10 blue-gre">blue-grey </div>
         <div class="p-10 blue-grey darken-1">blue-grey darken-1</div>
         <div class="p-10 blue-grey darken-2">blue-grey darken-2</div>
         <div class="p-10 blue-grey darken-3">blue-grey darken-3</div>
         <div class="p-10 blue-grey darken-4">blue-grey darken-4</div>
         <div class="p-10 blue-grey accent-1">blue-grey accent-1</div>
         <div class="p-10 blue-grey accent-2">blue-grey accent-2</div>
         <div class="p-10 blue-grey accent-3">blue-grey accent-3</div>
         <div class="p-10 blue-grey accent-4">blue-grey accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 black lighten-5">black </div>
         <div class="p-10 white  lighten-4">white </div>
      </div>
   </div>



   <div class="ar m-30 aione-border">
      <div class="aione-title">
         <h4 class="aione-align-center font-weight-100 aione-border-bottom pb-15">Background Color</h4>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-red lighten-5 aione-align-center black">bg-red lighten-5</div>
         <div class="p-10 bg-red lighten-4 aione-align-center black">bg-red lighten-4</div>
         <div class="p-10 bg-red lighten-3 aione-align-center black">bg-red lighten-3</div>
         <div class="p-10 bg-red lighten-2 aione-align-center black">bg-red lighten-2</div>
         <div class="p-10 bg-red lighten-1 aione-align-center black">bg-red lighten-1</div>
         <div class="p-10 bg-red aione-align-center black">bg-red</div>
         <div class="p-10 bg-red darken-1 aione-align-center black">bg-red darken-1</div>
         <div class="p-10 bg-red darken-2 aione-align-center black">bg-red darken-2</div>
         <div class="p-10 bg-red darken-3 aione-align-center black">bg-red darken-3</div>
         <div class="p-10 bg-red darken-4 aione-align-center black">bg-red darken-4</div>
         <div class="p-10 bg-red accent-1 aione-align-center black">bg-red accent-1</div>
         <div class="p-10 bg-red accent-2 aione-align-center black">bg-red accent-2</div>
         <div class="p-10 bg-red accent-3 aione-align-center black">bg-red accent-3</div>
         <div class="p-10 bg-red accent-4 aione-align-center black">bg-red accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-pink lighten-5 aione-align-center black">bg-pink lighten-5</div>
         <div class="p-10 bg-pink lighten-4 aione-align-center black">bg-pink lighten-4</div>
         <div class="p-10 bg-pink lighten-3 aione-align-center black">bg-pink lighten-3</div>
         <div class="p-10 bg-pink lighten-2 aione-align-center black">bg-pink lighten-2</div>
         <div class="p-10 bg-pink lighten-1 aione-align-center black">bg-pink lighten-1</div>
         <div class="p-10 bg-pink aione-align-center black">bg-pink</div>
         <div class="p-10 bg-pink darken-1 aione-align-center black">bg-pink darken-1</div>
         <div class="p-10 bg-pink darken-2 aione-align-center black">bg-pink darken-2</div>
         <div class="p-10 bg-pink darken-3 aione-align-center black">bg-pink darken-3</div>
         <div class="p-10 bg-pink darken-4 aione-align-center black">bg-pink darken-4</div>
         <div class="p-10 bg-pink accent-1 aione-align-center black">bg-pink accent-1</div>
         <div class="p-10 bg-pink accent-2 aione-align-center black">bg-pink accent-2</div>
         <div class="p-10 bg-pink accent-3 aione-align-center black">bg-pink accent-3</div>
         <div class="p-10 bg-pink accent-4 aione-align-center black">bg-pink accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-purple lighten-5 aione-align-center black">bg-purple lighten-5</div>
         <div class="p-10 bg-purple lighten-4 aione-align-center black">bg-purple lighten-4</div>
         <div class="p-10 bg-purple lighten-3 aione-align-center black">bg-purple lighten-3</div>
         <div class="p-10 bg-purple lighten-2 aione-align-center black">bg-purple lighten-2</div>
         <div class="p-10 bg-purple lighten-1 aione-align-center black">bg-purple lighten-1</div>
         <div class="p-10 bg-purple aione-align-center black">bg-purple</div>
         <div class="p-10 bg-purple darken- aione-align-center black">bg-purple darken-1</div>
         <div class="p-10 bg-purple darken-2 aione-align-center black">bg-purple darken-2</div>
         <div class="p-10 bg-purple darken-3 aione-align-center black">bg-purple darken-3</div>
         <div class="p-10 bg-purple darken-4 aione-align-center black">bg-purple darken-3</div>
         <div class="p-10 bg-purple accent- aione-align-center black">bg-purple accent-1</div>
         <div class="p-10 bg-purple accent-2 aione-align-center black">bg-purple accent-2</div>
         <div class="p-10 bg-purple accent-3 aione-align-center black">bg-purple accent-3</div>
         <div class="p-10 bg-purple accent-4 aione-align-center black">bg-purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-deep-purple lighten-5 aione-align-center black">bg-deep-purple lighten-5</div>
         <div class="p-10 bg-deep-purple lighten-4 aione-align-center black">bg-deep-purple lighten-4</div>
         <div class="p-10 bg-deep-purple lighten-3 aione-align-center black">bg-deep-purple lighten-3</div>
         <div class="p-10 bg-deep-purple lighten-2 aione-align-center black">bg-deep-purple lighten-2</div>
         <div class="p-10 bg-deep-purple lighten-1 aione-align-center black">bg-deep-purple lighten-1</div>
         <div class="p-10 bg-deep-purple aione-align-center black">bg-deep-purple</div>
         <div class="p-10 bg-deep-purple darken-1 aione-align-center black">bg-deep-purple darken-1</div>
         <div class="p-10 bg-deep-purple darken-2 aione-align-center black">bg-deep-purple darken-2</div>
         <div class="p-10 bg-deep-purple darken- 3 aione-align-center black">bg-deep-purple darken-3</div>
         <div class="p-10 bg-deep-purple darken-4 aione-align-center black">bg-deep-purple darken-4</div>
         <div class="p-10 bg-deep-purple accent-1 aione-align-center black">bg-deep-purple accent-1</div>
         <div class="p-10 bg-deep-purple accent-2 aione-align-center black">bg-deep-purple accent-2</div>
         <div class="p-10 bg-deep-purple accent-3 aione-align-center black">bg-deep-purple accent-3</div>
         <div class="p-10 bg-deep-purple accent-4 aione-align-center black">bg-deep-purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-indigo lighten-5 aione-align-center black">bg-indigo lighten-5</div>
         <div class="p-10 bg-indigo lighten-4 aione-align-center black">bg-indigo lighten-4</div>
         <div class="p-10 bg-indigo lighten-3 aione-align-center black">bg-indigo lighten-3</div>
         <div class="p-10 bg-indigo lighten-2 aione-align-center black">bg-indigo lighten-2</div>
         <div class="p-10 bg-indigo lighten-1 aione-align-center black">bg-indigo lighten-1</div>
         <div class="p-10 bg-indigo aione-align-center black">bg-indigo</div>
         <div class="p-10 bg-indigo darken-1 aione-align-center black">bg-indigo darken-1</div>
         <div class="p-10 bg-indigo darken-2 aione-align-center black">bg-indigo darken-2</div>
         <div class="p-10 bg-indigo darken-3 aione-align-center black">bg-indigo darken-3</div>
         <div class="p-10 bg-indigo darken-4 aione-align-center black">bg-indigo darken-4</div>
         <div class="p-10 bg-indigo accent-1 aione-align-center black">bg-indigo accent-1</div>
         <div class="p-10 bg-indigo accent-2 aione-align-center black">bg-indigo accent-2</div>
         <div class="p-10 bg-indigo accent-3 aione-align-center black">bg-indigo accent-3</div>
         <div class="p-10 bg-indigo accent-4 aione-align-center black">bg-indigo accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black">
         <div class="p-10 bg-blue lighten-5 aione-align-center ">bg-blue lighten-5</div>
         <div class="p-10 bg-blue lighten-4 aione-align-center ">bg-blue lighten-4</div>
         <div class="p-10 bg-blue lighten-3 aione-align-center ">bg-blue lighten-3</div>
         <div class="p-10 bg-blue lighten-2 aione-align-center ">bg-blue lighten-2</div>
         <div class="p-10 bg-blue lighten-1 aione-align-center ">bg-blue lighten-1</div>
         <div class="p-10 bg-blue aione-align-center">bg-blue</div>
         <div class="p-10 bg-blue darken-1 aione-align-center ">bg-blue darken-1</div>
         <div class="p-10 bg-blue darken-2 aione-align-center ">bg-blue darken-2</div>
         <div class="p-10 bg-blue darken-3 aione-align-center ">bg-blue darken-3</div>
         <div class="p-10 bg-blue darken-4 aione-align-center ">bg-blue darken-4</div>
         <div class="p-10 bg-blue accent-1 aione-align-center ">bg-blue accent-1</div>
         <div class="p-10 bg-blue accent-2 aione-align-center ">bg-blue accent-2</div>
         <div class="p-10 bg-blue accent-3 aione-align-center ">bg-blue accent-</div>
         <div class="p-10 bg-blue accent-4 aione-align-center ">bg-blue accent-</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-light-blue lighten-5 aione-align-center black">bg-light-blue lighten-5</div>
         <div class="p-10 bg-light-blue lighten-4 aione-align-center black">bg-light-blue lighten-4</div>
         <div class="p-10 bg-light-blue lighten-3 aione-align-center black">bg-light-blue lighten-3</div>
         <div class="p-10 bg-light-blue lighten-2 aione-align-center black">bg-light-blue lighten-2</div>
         <div class="p-10 bg-light-blue lighten-1 aione-align-center black">bg-light-blue lighten-1</div>
         <div class="p-10 bg-light-blue aione-align-center black">bg-light-blue</div>
         <div class="p-10 bg-light-blue darken-1 aione-align-center black">bg-light-blue darken-1</div>
         <div class="p-10 bg-light-blue darken-2 aione-align-center black">bg-light-blue darken-2</div>
         <div class="p-10 bg-light-blue darken-3 aione-align-center black">bg-light-blue darken-</div>
         <div class="p-10 bg-light-blue darken-4 aione-align-center black">bg-light-blue darken-4</div>
         <div class="p-10 bg-light-blue accent-1 aione-align-center black">bg-light-blue accent-1</div>
         <div class="p-10 bg-light-blue accent-2 aione-align-center black">bg-light-blue accent-2</div>
         <div class="p-10 bg-light-blue accent-3 aione-align-center black">bg-light-blue accent-3</div>
         <div class="p-10 bg-light-blue accent-4 aione-align-center black">bg-light-blue accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-cyan lighten-5  aione-align-center black">bg-cyan lighten-5</div>
         <div class="p-10 bg-cyan lighten-4 aione-align-center black">bg-cyan lighten-4</div>
         <div class="p-10 bg-cyan lighten-3 aione-align-center black">bg-cyan lighten-3</div>
         <div class="p-10 bg-cyan lighten-2 aione-align-center black">bg-cyan lighten-2</div>
         <div class="p-10 bg-cyan lighten-1 aione-align-center black">bg-cyan lighten-1</div>
         <div class="p-10 bg-cyan aione-align-center black">bg-cyan</div>
         <div class="p-10 bg-cyan darken-1 aione-align-center black">bg-cyan darken-1</div>
         <div class="p-10 bg-cyan darken-2 aione-align-center black">bg-cyan darken-2</div>
         <div class="p-10 bg-cyan darken-3 aione-align-center black">bg-cyan darken-3</div>
         <div class="p-10 bg-cyan darken-4 aione-align-center black">bg-cyan darken-4</div>
         <div class="p-10 bg-cyan accent-1 aione-align-center black">bg-cyan accent-1</div>
         <div class="p-10 bg-cyan accent-2 aione-align-center black">bg-cyan accent-2</div>
         <div class="p-10 bg-cyan accent-3 aione-align-center black">bg-cyan accent-3</div>
         <div class="p-10 bg-cyan accent-4 aione-align-center black">bg-cyan accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-teal lighten-5 aione-align-center black">bg-teal lighten-5</div>
         <div class="p-10 bg-teal lighten-4 aione-align-center black">bg-teal lighten-4</div>
         <div class="p-10 bg-teal lighten-3 aione-align-center black">bg-teal lighten-3</div>
         <div class="p-10 bg-teal lighten-2 aione-align-center black">bg-teal lighten-2</div>
         <div class="p-10 bg-teal lighten-1 aione-align-center black">bg-teal lighten-1</div>
         <div class="p-10 bg-teal aione-align-center black">bg-teal</div>
         <div class="p-10 bg-teal darken-1 aione-align-center black">bg-teal darken-1</div>
         <div class="p-10 bg-teal darken-2 aione-align-center black">bg-teal darken-2</div>
         <div class="p-10 bg-teal darken-3 aione-align-center black">bg-teal darken-3</div>
         <div class="p-10 bg-teal darken-4 aione-align-center black">bg-teal darken-4</div>
         <div class="p-10 bg-teal accent-1 aione-align-center black">bg-teal accent-1</div>
         <div class="p-10 bg-teal accent-2 aione-align-center black">bg-teal accent-2</div>
         <div class="p-10 bg-teal accent-3 aione-align-center black">bg-teal accent-3</div>
         <div class="p-10 bg-teal accent-4 aione-align-center black">bg-teal accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 aione-align-center black">
         <div class="p-10 bg-green lighten-5 ">bg-green lighten-5</div>
         <div class="p-10 bg-green lighten-4 ">bg-green lighten-4</div>
         <div class="p-10 bg-green lighten-3 ">bg-green lighten-3</div>
         <div class="p-10 bg-green lighten-2 ">bg-green lighten-2</div>
         <div class="p-10 bg-green lighten-1 ">bg-green lighten-1</div>
         <div class="p-10 bg-green">bg-green</div>
         <div class="p-10 bg-green darken-1 ">bg-green darken-1</div>
         <div class="p-10 bg-green darken-2 ">bg-green darken-2</div>
         <div class="p-10 bg-green darken-3 ">bg-green darken-3</div>
         <div class="p-10 bg-green darken-4 ">bg-green darken-4</div>
         <div class="p-10 bg-green accent-1 ">bg-green accent-1</div>
         <div class="p-10 bg-green accent-2 ">bg-green accent-2</div>
         <div class="p-10 bg-green accent-3 ">bg-green accent-3</div>
         <div class="p-10 bg-green accent-4 ">bg-green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-light-green lighten-5  ">bg-light-green lighten-5</div>
         <div class="p-10 bg-light-green lighten-4  ">bg-light-green lighten-4</div>
         <div class="p-10 bg-light-green lighten-3 ">bg-light-green lighten-3</div>
         <div class="p-10 bg-light-green lighten-2 ">bg-light-green lighten-2</div>
         <div class="p-10 bg-light-green lighten-1">bg-light-green lighten-1</div>
         <div class="p-10 bg-light-green">bg-light-green</div>
         <div class="p-10 bg-light-green darken-1 ">bg-light-green darken-1</div>
         <div class="p-10 bg-light-green darken-2  ">bg-light-green darken-2</div>
         <div class="p-10 bg-light-green darken-3 ">bg-light-green darken-</div>
         <div class="p-10 bg-light-green darken-4 ">bg-light-green darken-4</div>
         <div class="p-10 bg-light-green accent-1 ">bg-light-green accent-1</div>
         <div class="p-10 bg-light-green accent-2 ">bg-light-green accent-2</div>
         <div class="p-10 bg-light-green accent-3 ">bg-light-green accent-3</div>
         <div class="p-10 bg-light-green accent-4">bg-light-green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-lime lighten-5">bg-lime lighten-5</div>
         <div class="p-10 bg-lime lighten-4">bg-lime lighten-4</div>
         <div class="p-10 bg-lime lighten-3">bg-lime lighten-3</div>
         <div class="p-10 bg-lime lighten-2">bg-lime lighten-2</div>
         <div class="p-10 bg-lime lighten-1">bg-lime lighten-1</div>
         <div class="p-10 bg-lime">bg-lime</div>
         <div class="p-10 bg-lime darken-1">bg-lime darken-1</div>
         <div class="p-10 bg-lime darken-2">bg-lime darken-2</div>
         <div class="p-10 bg-lime darken-3">bg-lime darken-3</div>
         <div class="p-10 bg-lime darken-4">bg-lime darken-4</div>
         <div class="p-10 bg-lime accent-1">bg-lime accent-1</div>
         <div class="p-10 bg-lime accent-2">bg-lime accent-2</div>
         <div class="p-10 bg-lime accent-3">bg-lime accent-3</div>
         <div class="p-10 bg-lime accent-4">bg-lime accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-yellow lighten-5">bg-yellow lighten-5</div>
         <div class="p-10 bg-yellow lighten-4">bg-yellow lighten-4</div>
         <div class="p-10 bg-yellow lighten-3">bg-yellow lighten-3</div>
         <div class="p-10 bg-yellow lighten-2">bg-yellow lighten-2</div>
         <div class="p-10 bg-yellow lighten-1">bg-yellow lighten-1</div>
         <div class="p-10 bg-yellow">bg-yellow</div>
         <div class="p-10 bg-yellow darken-1">bg-yellow darken-1</div>
         <div class="p-10 bg-yellow darken-2">bg-yellow darken-2</div>
         <div class="p-10 bg-yellow darken-3">bg-yellow darken-3</div>
         <div class="p-10 bg-yellow darken-4">bg-yellow darken-4</div>
         <div class="p-10 bg-yellow accent-1">bg-yellow accent-1</div>
         <div class="p-10 bg-yellow accent-2">bg-yellow accent-2</div>
         <div class="p-10 bg-yellow accent-3">bg-yellow accent-3</div>
         <div class="p-10 bg-yellow accent-4">bg-yellow accent-</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-amber lighten-5">bg-amber lighten-5</div>
         <div class="p-10 bg-amber lighten-4">bg-amber lighten-4</div>
         <div class="p-10 bg-amber lighten-3">bg-amber lighten-3</div>
         <div class="p-10 bg-amber lighten-2">bg-amber lighten-2</div>
         <div class="p-10 bg-amber lighten-1">bg-amber lighten-1</div>
         <div class="p-10 bg-amber">bg-amber</div>
         <div class="p-10 bg-amber darken-1">bg-amber darken-1</div>
         <div class="p-10 bg-amber darken-2">bg-amber darken-2</div>
         <div class="p-10 bg-amber darken-3">bg-amber darken-3</div>
         <div class="p-10 bg-amber darken-4">bg-amber darken-4</div>
         <div class="p-10 bg-amber accent-1">bg-amber accent-1</div>
         <div class="p-10 bg-amber accent-2">bg-amber accent-2</div>
         <div class="p-10 bg-amber accent-3">bg-amber accent-3</div>
         <div class="p-10 bg-amber accent-4">bg-amber accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-orange lighten-5 ">bg-orange lighten-5</div>
         <div class="p-10 bg-orange lighten-4">bg-orange lighten-4</div>
         <div class="p-10 bg-orange lighten-3">bg-orange lighten-3</div>
         <div class="p-10 bg-orange lighten-2">bg-orange lighten-2</div>
         <div class="p-10 bg-orange lighten-1">bg-orange lighten-1</div>
         <div class="p-10 bg-orange">bg-orange</div>
         <div class="p-10 bg-orange darken-1">bg-orange darken-1</div>
         <div class="p-10 bg-orange darken-2">bg-orange darken-2</div>
         <div class="p-10 bg-orange darken-3">bg-orange darken-3</div>
         <div class="p-10 bg-orange darken-4">bg-orange darken-4</div>
         <div class="p-10 bg-orange accent-1">bg-orange accent-1</div>
         <div class="p-10 bg-orange accent-2">bg-orange accent-2</div>
         <div class="p-10 bg-orange accent-3">bg-orange accent-3</div>
         <div class="p-10 bg-orange accent-4">bg-orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-deep-orange lighten-5">bg-deep-orange lighten-5</div>
         <div class="p-10 bg-deep-orange lighten-4">bg-deep-orange lighten-4</div>
         <div class="p-10 bg-deep-orange lighten-3">bg-deep-orange lighten-3</div>
         <div class="p-10 bg-deep-orange lighten-2">bg-deep-orange lighten-2</div>
         <div class="p-10 bg-deep-orange lighten-1">bg-deep-orange lighten-1</div>
         <div class="p-10 bg-deep-orange">bg-deep-orange</div>
         <div class="p-10 bg-deep-orange darken-1">bg-deep-orange darken-1</div>
         <div class="p-10 bg-deep-orange darken-2">bg-deep-orange darken-2</div>
         <div class="p-10 bg-deep-orange darken-3">bg-deep-orange darken-3</div>
         <div class="p-10 bg-deep-orange darken-4">bg-deep-orange darken-4</div>
         <div class="p-10 bg-deep-orange accent-1">bg-deep-orange accent-1</div>
         <div class="p-10 bg-deep-orange accent-2">bg-deep-orange accent-2</div>
         <div class="p-10 bg-deep-orange accent-3">bg-deep-orange accent-3</div>
         <div class="p-10 bg-deep-orange accent-4">bg-deep-orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-brown lighten-5 ">bg-brown lighten-5</div>
         <div class="p-10 bg-brown lighten-4 ">bg-brown lighten-4</div>
         <div class="p-10 bg-brown lighten-3 ">bg-brown lighten-3</div>
         <div class="p-10 bg-brown lighten-2 ">bg-brown lighten-2</div>
         <div class="p-10 bg-brown lighten-1 ">bg-brown lighten-1</div>
         <div class="p-10 bg-brown ">bg-brown</div>
         <div class="p-10 bg-brown darken-1 ">bg-brown darken-1</div>
         <div class="p-10 bg-brown darken-2 ">bg-brown darken-2</div>
         <div class="p-10 bg-brown darken-3 ">bg-brown darken-3</div>
         <div class="p-10 bg-brown darken-4 ">bg-brown darken-4</div>

      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-grey lighten-5">bg-grey lighten-5</div>
         <div class="p-10 bg-grey lighten-4">bg-grey lighten-4</div>
         <div class="p-10 bg-grey lighten-3">bg-grey lighten-3</div>
         <div class="p-10 bg-grey lighten-2">bg-grey lighten-2</div>
         <div class="p-10 bg-grey lighten-1">bg-grey lighten-1</div>
         <div class="p-10 bg-grey">bg-grey</div>
         <div class="p-10 bg-grey darken-1">bg-grey darken-1</div>
         <div class="p-10 bg-grey darken-2">bg-grey darken-2</div>
         <div class="p-10 bg-grey darken-3">bg-grey darken-3</div>
         <div class="p-10 bg-grey darken-4">bg-grey darken-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 bg-blue-grey  lighten-5 ">bg-blue-grey lighten-5</div>
         <div class="p-10 bg-blue-grey  lighten-4 ">bg-blue-grey lighten-4</div>
         <div class="p-10 bg-blue-grey  lighten-3 ">bg-blue-grey lighten-3</div>
         <div class="p-10 bg-blue-grey  lighten-2 ">bg-blue-grey lighten-2</div>
         <div class="p-10 bg-blue-grey  lighten-1 ">bg-blue-grey lighten-1</div>
         <div class="p-10 bg-blue-grey  ">bg-blue-grey</div>
         <div class="p-10 bg-blue-grey  darken-1 ">bg-blue-grey darken-1</div>
         <div class="p-10 bg-blue-grey  darken-2 ">bg-blue-grey darken-2</div>
         <div class="p-10 bg-blue-grey  darken-3 ">bg-blue-grey darken-3</div>
         <div class="p-10 bg-blue-grey  darken-4 ">bg-blue-grey darken-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 bg-black  lighten-5 aione-align-center">black</div>
         <div class="p-10 bg-white  lighten-4 aione-align-center">white</div>
      </div>
   </div>


   <div class="ar m-30 aione-border">
      <div class="aione-title">
         <h4 class="aione-align-center font-weight-100 aione-border-bottom pb-15">Border Color</h4>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-red lighten-5 bg-white aione-align-center ">border-red lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red lighten-4 bg-white aione-align-center ">border-red lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red lighten-3 bg-white aione-align-center ">border-red lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red lighten-2 bg-white aione-align-center ">border-red lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red lighten-1 bg-white aione-align-center ">border-red lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red bg-white aione-align-center ">border-red</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red darken-1 bg-white aione-align-center ">border-red darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red darken-2 bg-white aione-align-center ">border-red darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red darken-3 bg-white aione-align-center ">border-red darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red darken-4 bg-white aione-align-center ">border-red darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red accent-1 bg-white aione-align-center ">border-red accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red accent-2 bg-white aione-align-center ">border-red accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red accent-3 bg-white aione-align-center ">border-red accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-red accent-4 bg-white aione-align-center ">border-red accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-pink lighten-5 bg-white aione-align-center ">border-pink lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink lighten-4 bg-white aione-align-center ">border-pink lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink lighten-3 bg-white aione-align-center ">border-pink lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink lighten-2 bg-white aione-align-center ">border-pink lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink lighten-1 bg-white aione-align-center ">border-pink lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink bg-white aione-align-center ">border-pink</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink darken-1 bg-white aione-align-center ">border-pink darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink darken-2 bg-white aione-align-center ">border-pink darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink darken-3 bg-white aione-align-center ">border-pink darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink darken-4 bg-white aione-align-center ">border-pink darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink accent-1 bg-white aione-align-center ">border-pink accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink accent-2 bg-white aione-align-center ">bg-pink accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink accent-3 bg-white aione-align-center ">border-pink accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-pink accent-4 bg-white aione-align-center ">border-pink accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-purple lighten-5 bg-white aione-align-center ">border-purple lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple lighten-4 bg-white aione-align-center ">border-purple lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple lighten-3 bg-white aione-align-center ">border-purple lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple lighten-2 bg-white aione-align-center ">border-purple lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple lighten-1 bg-white aione-align-center ">border-purple lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple bg-white aione-align-center ">border-purple</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple darken- bg-white aione-align-center ">border-purple darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple darken-2 bg-white aione-align-center ">border-purple darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple darken-3 bg-white aione-align-center ">border-purple darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple darken-4 bg-white aione-align-center ">border-purple darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple accent- bg-white aione-align-center ">border-purple accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple accent-2 bg-white aione-align-center ">border-purple accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple accent-3 bg-white aione-align-center ">border-purple accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-purple accent-4 bg-white aione-align-center ">border-purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple lighten-5 bg-white aione-align-center ">border-deep-purple lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple lighten-4 bg-white aione-align-center ">border-deep-purple lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple lighten-3 bg-white aione-align-center ">border-deep-purple lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple lighten-2 bg-white aione-align-center ">border-deep-purple lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple lighten-1 bg-white aione-align-center ">border-deep-purple lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple bg-white aione-align-center ">border-deep-purple</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple darken-1 bg-white aione-align-center ">border-deep-purple darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple darken-2 bg-white aione-align-center ">border-deep-purple darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple darken- 3 bg-white aione-align-center ">border-deep-purple darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple darken-4 bg-white aione-align-center ">border-deep-purple darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple accent-1 bg-white aione-align-center ">border-deep-purple accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple accent-2 bg-white aione-align-center ">border-deep-purple accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple accent-3 bg-white aione-align-center ">border-deep-purple accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-purple accent-4 bg-white aione-align-center ">border-deep-purple accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo lighten-5 bg-white aione-align-center ">border-indigo lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo lighten-4 bg-white aione-align-center ">border-indigo lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo lighten-3 bg-white aione-align-center ">border-indigo lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo lighten-2 bg-white aione-align-center ">border-indigo lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo lighten-1 bg-white aione-align-center ">border-indigo lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo bg-white aione-align-center ">border-indigo</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo darken-1 bg-white aione-align-center ">border-indigo darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo darken-2 bg-white aione-align-center ">border-indigo darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo darken-3 bg-white aione-align-center ">border-indigo darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo darken-4 bg-white aione-align-center ">border-indigo darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo accent-1 bg-white aione-align-center ">border-indigo accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo accent-2 bg-white aione-align-center ">border-indigo accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo accent-3 bg-white aione-align-center ">border-indigo accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-indigo accent-4 bg-white aione-align-center ">border-indigo accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black">
         <div class="p-10 mb-5 aione-border border-width-5 border-blue lighten-5 aione-align-center ">border-blue lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue lighten-4 aione-align-center ">border-blue lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue lighten-3 aione-align-center ">border-blue lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue lighten-2 aione-align-center ">border-blue lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue lighten-1 aione-align-center ">border-blue lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue aione-align-center">border-blue</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue darken-1 aione-align-center ">border-blue darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue darken-2 aione-align-center ">border-blue darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue darken-3 aione-align-center ">border-blue darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue darken-4 aione-align-center ">border-blue darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue accent-1 aione-align-center ">border-blue accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue accent-2 aione-align-center ">border-blue accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue accent-3 aione-align-center ">border-blue accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue accent-4 aione-align-center ">border-blue accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue lighten-5 bg-white aione-align-center ">border-light-blue lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue lighten-4 bg-white aione-align-center ">border-light-blue lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue lighten-3 bg-white aione-align-center ">border-light-blue lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue lighten-2 bg-white aione-align-center ">border-light-blue lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue lighten-1 bg-white aione-align-center ">border-light-blue lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue bg-white aione-align-center ">border-light-blue</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue darken-1 bg-white aione-align-center ">border-light-blue darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue darken-2 bg-white aione-align-center ">border-light-blue darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue darken-3 bg-white aione-align-center ">border-light-blue darken-</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue darken-4 bg-white aione-align-center ">border-light-blue darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue accent-1 bg-white aione-align-center ">border-light-blue accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue accent-2 bg-white aione-align-center ">border-light-blue accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue accent-3 bg-white aione-align-center ">border-light-blue accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-blue accent-4 bg-white aione-align-center ">border-light-blue accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan lighten-5  bg-white aione-align-center ">border-cyan lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan lighten-4 bg-white aione-align-center ">border-cyan lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan lighten-3 bg-white aione-align-center ">border-cyan lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan lighten-2 bg-white aione-align-center ">border-cyan lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan lighten-1 bg-white aione-align-center ">border-cyan lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan bg-white aione-align-center ">border-cyan</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan darken-1 bg-white aione-align-center ">border-cyan darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan darken-2 bg-white aione-align-center ">border-cyan darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan darken-3 bg-white aione-align-center ">border-cyan darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan darken-4 bg-white aione-align-center ">border-cyan darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan accent-1 bg-white aione-align-center ">border-cyan accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan accent-2 bg-white aione-align-center ">border-cyan accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan accent-3 bg-white aione-align-center ">border-cyan accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-cyan accent-4 bg-white aione-align-center ">border-cyan accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-teal lighten-5 bg-white aione-align-center ">border-teal lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal lighten-4 bg-white aione-align-center ">border-teal lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal lighten-3 bg-white aione-align-center ">border-teal lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal lighten-2 bg-white aione-align-center ">border-teal lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal lighten-1 bg-white aione-align-center ">border-teal lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal bg-white aione-align-center ">border-teal</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal darken-1 bg-white aione-align-center ">border-teal darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal darken-2 bg-white aione-align-center ">border-teal darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal darken-3 bg-white aione-align-center ">border-teal darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal darken-4 bg-white aione-align-center ">border-teal darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal accent-1 bg-white aione-align-center ">border-teal accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal accent-2 bg-white aione-align-center ">border-teal accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal accent-3 bg-white aione-align-center ">border-teal accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-teal accent-4 bg-white aione-align-center ">border-teal accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 bg-white aione-align-center ">
         <div class="p-10 mb-5 aione-border border-width-5 border-green lighten-5 ">border-green lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green lighten-4 ">border-green lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green lighten-3 ">border-green lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green lighten-2 ">border-green lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green lighten-1 ">border-green lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green">border-green</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green darken-1 ">border-green darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green darken-2 ">border-green darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green darken-3 ">border-green darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green darken-4 ">border-green darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green accent-1 ">border-green accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green accent-2 ">border-green accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green accent-3 ">border-green accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-green accent-4 ">border-green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green lighten-5  ">border-light-green lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green lighten-4  ">border-light-green lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green lighten-3 ">border-light-green lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green lighten-2 ">border-light-green lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green lighten-1">border-light-green lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green">border-light-green</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green darken-1 ">border-light-green darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green darken-2  ">border-light-green darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green darken-3 ">border-light-green darken-</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green darken-4 ">border-light-green darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green accent-1 ">border-light-green accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green accent-2 ">border-light-green accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green accent-3 ">border-light-green accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-light-green accent-4">border-light-green accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-lime lighten-5">border-lime lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime lighten-4">border-lime lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime lighten-3">border-lime lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime lighten-2">border-lime lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime lighten-1">border-lime lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime">border-lime</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime darken-1">border-lime darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime darken-2">border-lime darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime darken-3">border-lime darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime darken-4">border-lime darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime accent-1">border-lime accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime accent-2">border-lime accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime accent-3">border-lime accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-lime accent-4">border-lime accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow lighten-5">border-yellow lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow lighten-4">border-yellow lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow lighten-3">border-yellow lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow lighten-2">border-yellow lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow lighten-1">border-yellow lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow">border-yellow</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow darken-1">border-yellow darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow darken-2">border-yellow darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow darken-3">border-yellow darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow darken-4">border-yellow darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow accent-1">border-yellow accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow accent-2">border-yellow accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow accent-3">border-yellow accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-yellow accent-4">border-yellow accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-amber lighten-5">border-amber lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber lighten-4">border-amber lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber lighten-3">border-amber lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber lighten-2">border-amber lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber lighten-1">border-amber lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber">border-amber</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber darken-1">border-amber darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber darken-2">border-amber darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber darken-3">border-amber darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber darken-4">border-amber darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber accent-1">border-amber accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber accent-2">border-amber accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber accent-3">border-amber accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-amber accent-4">border-amber accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-orange lighten-5 ">border-orange lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange lighten-4">border-orange lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange lighten-3">border-orange lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange lighten-2">border-orange lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange lighten-1">border-orange lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange">border-orange</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange darken-1">border-orange darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange darken-2">border-orange darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange darken-3">border-orange darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange darken-4">border-orange darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange accent-1">border-orange accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange accent-2">border-orange accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange accent-3">border-orange accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-orange accent-4">border-orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange lighten-5">border-deep-orange lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange lighten-4">border-deep-orange lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange lighten-3">border-deep-orange lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange lighten-2">border-deep-orange lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange lighten-1">border-deep-orange lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange">border-deep-orange</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange darken-1">border-deep-orange darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange darken-2">border-deep-orange darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange darken-3">border-deep-orange darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange darken-4">border-deep-orange darken-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange accent-1">border-deep-orange accent-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange accent-2">border-deep-orange accent-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange accent-3">border-deep-orange accent-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-deep-orange accent-4">border-deep-orange accent-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-brown lighten-5 ">border-brown lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown lighten-4 ">border-brown lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown lighten-3 ">border-brown lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown lighten-2 ">border-brown lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown lighten-1 ">border-brown lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown ">border-brown</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown darken-1 ">border-brown darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown darken-2 ">border-brown darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown darken-3 ">border-brown darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-brown darken-4 ">border-brown darken-4</div>

      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-grey lighten-5">border-grey lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey lighten-4">border-grey lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey lighten-3">border-grey lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey lighten-2">border-grey lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey lighten-1">border-grey lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey">border-grey</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey darken-1">border-grey darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey darken-2">border-grey darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey darken-3">border-grey darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-grey darken-4">border-grey darken-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15 black aione-align-center">
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  lighten-5 ">border-blue-grey lighten-5</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  lighten-4 ">border-blue-grey lighten-4</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  lighten-3 ">border-blue-grey lighten-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  lighten-2 ">border-blue-grey lighten-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  lighten-1 ">border-blue-grey lighten-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  ">border-blue-grey</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  darken-1 ">border-blue-grey darken-1</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  darken-2 ">border-blue-grey darken-2</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  darken-3 ">border-blue-grey darken-3</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-blue-grey  darken-4 ">border-blue-grey darken-4</div>
      </div>
      <div class="ac s100 m33 l20 mb-15">
         <div class="p-10 mb-5 aione-border border-width-5 border-black  lighten-5 aione-align-center">black</div>
         <div class="p-10 mb-5 aione-border border-width-5 border-white  lighten-4 aione-align-center">white</div>
      </div>
   </div>

</body>

</html>